# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
  return 1/(1+np.exp(-x))

x=np.linspace(-10,10,1000)

y=sigmoid(x)

plt.figure(figsize=(8,6))
plt.plot(x,y,label="Sigmodal Function")
plt.title("Sigmoid function")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.show()

